# Base de datos para escritura
DATABASE_WRITE_URL=${DATABASE_WRITE_URL}
DATABASE_WRITE_USER=${DATABASE_WRITE_USER}
DATABASE_WRITE_PASSWORD=${DATABASE_WRITE_PASSWORD}

# Base de datos para lectura
DATABASE_URL=${DATABASE_URL}
DATABASE_USER=${DATABASE_USER}
DATABASE_PASSWORD=${DATABASE_PASSWORD}
